project:
  render:
        - "*.qmd"
        - "!memos/"
bibliography: library.bib
format:
  pdf:
    keep-tex: true
    mainfont: TeX Gyre Pagella
    mathfont: TeX Gyre Pagella
    pdf-engine: lualatex
