# -*- mode: yaml-ts -*-
project:
  render:
        - "*.qmd"
        - "!memos/"
bibliography: library.bib
format:
  pdf:
    fontsize: 11pt
    papersize: A4
    include-in-header:
        - text: |
            \usepackage[font={small}]{caption}
            \definecolor{pastelblue}{HTML}{579ABE}
            \definecolor{pastelgreen}{HTML}{03C03C}
    linkcolor: pastelblue
    urlcolor: pastelgreen
    citecolor: pastelblue
    link-citations: true
    keep-tex: true
    mainfont: TeX Gyre Pagella
    mathfont: TeX Gyre Pagella Math
    pdf-engine: lualatex
    knitr:
        opts_chunk:
            dev: cairo_pdf
