#+TITLE: Onset of Frozen Conflicts
#+AUTHOR: JLA Krusell


*Research question*: /why do conflicts become frozen?/

Re-phrased, why do conflicts not terminate in conclusive victory
and/or peace agreements? How do rebel groups maintain credible threats
against the state?

Cunningham - Rebel strength dataset?

* TODO Next research memo

- Frozen conflict definition, conceptualization
- Datasets
- Initial models


* DONE Descriptive statistics
CLOSED: [2023-01-10 Tue 08:23]

- State "STARTED"    from "WAITING"    [2023-01-10 Tue 08:22]
- State "WAITING"    from "TODO"       [2023-01-10 Tue 08:22]
ETH/PRIO ceasefire dataset

* Model

Dyadic-level relationship?

Level of analysis - episodes (either dyadic/conflict IDs)

binary variable, ${0, 1}$, outcome

\begin{equation}
y_{ij} & \sim \text{Binomial}(\pi_{ij}) \\

\end{equation}

* Data

** Case - Armenia/Artsakh & Azerbaijan

UCDP =dyad_id= 833

=side_a= - Government of Azerbaijan
=side_b= - Republic of Artsakh
=side_b_2nd= - Government of Armenia

** Ceasefire dataset

Note: =truce= variable not mentioned in documentation

Note: =ended= - 4 not mentioned in documentation

actor_name
ucdp_dyad
pax_id
cf_dec_yr
cf_effect_yr
ended
timing
truce

- =side= :: 1 - unilateral, 2 - bilateral, 3 - multilateral

** UCDP Dyadic Dataset

- =location= :: Name of country/countries

** FCD - Frozen Conflict Dataset

1946 - 2011, "...a frozen conflict comes into being in same year in
which a major interstate or intrastate war with *500* battle deaths
concluded and the interest incompatibility between the conflict actors
was not resolved."

interstate dyads had to also experience at least *4 militarized
interstate disputes* within 20 years after the initial war ended.

=country_a= is always a state, =country_b= can be state/non-state actor

- =conflictstart_y= :: "Start year of the Frozen Conflict. It
  constitutes the last year in which the preceding war measured above
  the threshold of 500 fatalities."

- =conflictend_t= :: 1 - Violent thawing. 2 - Peaceful thawing. 3 -
  Conflict Withering

- =type_conflict= :: 0 - interstate, 1 - intrastate

- =onset_war_above_1000= :: whether initial war surpassed threshold of
  1000 BRD


** ESD - External Support Dataset

142 dyads present in UCDP Dyadic dataset, but not in ESD

Note: do *not* use dyadic level dataset, since it doesn't distinguish
between support to /which/ actor in the conflict

- =actor_id= :: does *not* correspond to =side_a_id=

- =actor_nonstate= :: variable identifying all obs where the potential
  support recipient is a non-state actor

- =dyad_id= :: corresponds to UCDP dyadic dataset

- =conflict_id= :: unique identifier of the conflict according to ACD 18.1

*** TODO Track down dyad_id differences b/w ESD and UCDP Dyadic

=setdiff(dyadic$dyad_id, esd$dyad_id)=
