---
title: Coding Protocol v0.1
author: J.L.A. Krusell
format: pdf
---

TODO: manual coding, specific criteria for determining when an actor ceases to exist
TODO: how to handle actor fragmentation? Ex: Sendero Luminoso
TODO: Be specific about sources that will be used, reference list?

The dataset was created using a mix of programmatic and manual coding in a two-stage process. The first stage filtered out dyadic civil conflict episode outcomes according to a preset list of rules listed in detail below. This candidate list was then manually corrected in the second stage to form the final list of frozen conflict onsets.

## Coding Procedure

### Stage 1

Dyadic conflict episode outcomes were drawn from the UCDP Conflict Termination dataset v21.1. This means that the definition of a conflict episode and its corresponding termination followed the coding conventions of the UCDP dataset. Namely, dyad-years are coded as active conflicts when the number of battle related fatalities rises above a threshold of 25. Consecutive conflict years, or episodes, are terminated the first year when this number drops below the threshold.

Episode outcomes were selected as potential onsets of frozen civil conflicts when satisfying the following predicates:

- Intrastate and internationalized intrastate conflicts --- *i.e.*, when the UCDP variable $\text{type\_of\_conflict}_i \in \{ 3, 4 \}$

- Outcomes were not coded as either a one-sided military victory or actor death --- *i.e.*, when the UCDP variable $\text{outcome}_i \notin \{ 3, 4, 6 \}$

- No comprehensive peace agreement lasting at least one calendar year signed either in the termination year or the subsequent year. This corresponds to when the UCDP variable $\text{pa\_type} = 1$ while duration was calculated based on the date of the last signature.

The last predicate relied on data drawn from the UCDP Peace Agreement dataset v22.1. Due to the smaller time series in the Peace Agreement dataset, the final list was restricted to conflict outcomes between 1975 and 2019.

```{r echo = F}
candidates <- read.csv("../data/dyadic_candidates.csv")
episodes <- read.csv("../data/dyadic_episodes.csv")
```

In total, `r nrow(candidates)` candidates were identified, comprising approximately
`r sprintf("%.2f", 100 * nrow(candidates) / sum(!is.na(episodes$outcome)))` percent of all outcomes.

### Stage 2

The resulting list was then manually coded to filter out episode outcomes where the non-state actor ceased to exist as a military actor within five years of termination. This includes situations where, for example, the rebel group unilaterally renounces violence as a political strategy and transitions to becoming a political party. Or, when a rebel group becomes so weakened and/or fragmented that they effectively dissolve.

Evaluations were primarily using a mix of UCDP's own description of conflicts and conflict actors, as well as a number of different academic sources.

Since there is a degree of subjectivity in evaluating edge cases, the dataset also includes a short comment justifying the coding as well as a self-reported confidence score.
